In [3]:
import numpy as np

In [7]:
n =  np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10])
print(np.sum(n))
print(np.size(n))
print(np.max(n))
print(np.min(n))
print(np.mean(n))
print(np.median(n))
# print(np.mode(n))

65
11
10
1
5.909090909090909
6.0

In [9]:
n = np.array([10, 20, 30, 40, 50])
print(np.cumsum(n))
print(np.cumprod(n))

[ 10  30  60 100 150]
[      10      200     6000   240000 12000000]

In [11]:
t = np.array([[1, 2], [4, 5]])
print(np.cumsum(t))
print(np.cumprod(t))

[ 1  3  7 12]
[ 1  2  8 40]

In [12]:
q = np.array([[[4, 2, 3], [4, 5, 6], [6, 7, 8]]])
print(np.cumsum(q))
print(np.cumprod(q))

[ 4  6  9 13 18 24 30 37 45]
[     4      8     24     96    480   2880  17280 120960 967680]

In [14]:
n = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(n)
print(np.sum(n, axis = 0))
print(np.sum(n, axis = 1))

[[10 20 30]
 [40 50 60]]
[50 70 90]
[ 60 150]

In [21]:
q = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])

print(q)

print(np.sum(q, axis = 0))
print(np.sum(q, axis = 1))
print(np.sum(q, axis = 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12 15 18]]
[[ 6 15 24]]

In [23]:
import pandas as pd
import numpy as np

In [25]:
s1 = pd.Series()
print(s1)

s2 = np.array([1, 2, 3, 4, 5])
s3 = pd.Series(s2)
print(s3)

Series([], dtype: object)
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [26]:
s4 = pd.Series([1, 2, 4, 5, 6])
print(s4)

0    1
1    2
2    4
3    5
4    6
dtype: int64

In [ ]:
# Customised Indexing
s5 = pd.Series(["aman", "chaman", "sonu", "monu"], index = ["A", "B", "C", "D"])
print(s5)

A      aman
B    chaman
C      sonu
D      monu
dtype: object

In [ ]:
s6 = pd.Series([10, 20, 30, 40, 50, 60])
print(s6.index)
print(s6.shape) # for dimension
print(s6.size)
print(s6.values)
print(s6.dtype) # type for data

RangeIndex(start=0, stop=6, step=1)
(6,)
6
[10 20 30 40 50 60]
int64

In [37]:
# 1 way to create 2D dataset
data = [
    [1, "Harnoor", "Entreprenuer", 340000, "Noida"],
    [2, "Aditi", "CEO", 56000, "Delhi"],
    [3, "Hari", "HR", 55000, "Haryana"],
    [4, "Aryan", "Teacher", 67000, "Goa"],
    [5, "Ravi", "Doctor", 56000, "Mumbai"],
    ]

df = pd.DataFrame(data, columns = ["ID", "Name", "Post", "Salary", "City"])
print(df)

   ID     Name          Post  Salary     City
0   1  Harnoor  Entreprenuer  340000    Noida
1   2    Aditi           CEO   56000    Delhi
2   3     Hari            HR   55000  Haryana
3   4    Aryan       Teacher   67000      Goa
4   5     Ravi        Doctor   56000   Mumbai

In [40]:
# 2nd Way 2D Dataset

emp  = {
    "id" : [1, 2, 3],
    "Name" : ["Harnoor", "Sahil", "Aditi"],
    "post" : ["Developer", "HR", "Manager"],
    "salary" : [1200, 3450, 6600],
    "city" : ["Noida", "goa", "Punjab"]
}
df = pd.DataFrame(emp)
df

   id     Name       post  salary    city
0   1  Harnoor  Developer    1200   Noida
1   2    Sahil         HR    3450     goa
2   3    Aditi    Manager    6600  Punjab

In [ ]:
print(df["Name"])
df.head(2)
df.tail(2)

0    Harnoor
1      Sahil
2      Aditi
Name: Name, dtype: object

   id   Name     post  salary    city
1   2  Sahil       HR    3450     goa
2   3  Aditi  Manager    6600  Punjab

In [44]:
df[df["salary"] > 1500]

   id   Name     post  salary    city
1   2  Sahil       HR    3450     goa
2   3  Aditi  Manager    6600  Punjab

In [49]:
df[(df["salary"] < 3500) & (df["salary"] >= 2500)]

   id   Name post  salary city
1   2  Sahil   HR    3450  goa

In [52]:
df["salary"].max()

np.int64(6600)

In [53]:
df["salary"].min()

np.int64(1200)

In [55]:
print(df[["Name", "post", "salary"]])

      Name       post  salary
0  Harnoor  Developer    1200
1    Sahil         HR    3450
2    Aditi    Manager    6600

In [57]:
# How to add column
df["Age"] = [67, 88, 33]
df

   id     Name       post  salary    city  Age
0   1  Harnoor  Developer    1200   Noida   67
1   2    Sahil         HR    3450     goa   88
2   3    Aditi    Manager    6600  Punjab   33

In [58]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Harnoor", "Aditi", "Harsharan", "Ekam", "Isha", "Simran", "Karan", "Navya", "Arjun", "Mehak"],
    "Post": ["Developer", "Data Analyst", "Manager", "Designer", "Tester", "Developer", "HR Executive", "Data Scientist", "Software Engineer", "Accountant"],
    "Salary": [45000, 38000, 65000, 42000, 35000, 52000, 40000, 70000, 58000, 36000],
    "City": ["Mohali", "Chandigarh", "Ludhiana", "Amritsar", "Patiala", "Delhi", "Jaipur", "Bangalore", "Pune", "Jalandhar"],
    "Age": [20, 22, 28, 24, 23, 26, 27, 29, 25, 30]
}

df2 = pd.DataFrame(data)

print(df2)

    ID       Name               Post  Salary        City  Age
0  101    Harnoor          Developer   45000      Mohali   20
1  102      Aditi       Data Analyst   38000  Chandigarh   22
2  103  Harsharan            Manager   65000    Ludhiana   28
3  104       Ekam           Designer   42000    Amritsar   24
4  105       Isha             Tester   35000     Patiala   23
5  106     Simran          Developer   52000       Delhi   26
6  107      Karan       HR Executive   40000      Jaipur   27
7  108      Navya     Data Scientist   70000   Bangalore   29
8  109      Arjun  Software Engineer   58000        Pune   25
9  110      Mehak         Accountant   36000   Jalandhar   30

In [ ]:
''' 1. add column bonus >= 40000 5% bonus 
    2. HRA 10 %
    3. DA 5 % 
    4. Calculate Gross Salary
    5. Calculate Net Salary
    
'''

In [72]:
df2.pop("HRA")

0    4500.0
1    3800.0
2    6500.0
3    4200.0
4    3500.0
5    5200.0
6    4000.0
7    7000.0
8    5800.0
9    3600.0
Name: HRA, dtype: float64

In [74]:
df2["Bonus"] = (df2["Salary"] > 40000) * df2["Salary"] * 0.05
df2

    ID       Name               Post  Salary        City  Age   Bonus
0  101    Harnoor          Developer   45000      Mohali   20  2250.0
1  102      Aditi       Data Analyst   38000  Chandigarh   22     0.0
2  103  Harsharan            Manager   65000    Ludhiana   28  3250.0
3  104       Ekam           Designer   42000    Amritsar   24  2100.0
4  105       Isha             Tester   35000     Patiala   23     0.0
5  106     Simran          Developer   52000       Delhi   26  2600.0
6  107      Karan       HR Executive   40000      Jaipur   27     0.0
7  108      Navya     Data Scientist   70000   Bangalore   29  3500.0
8  109      Arjun  Software Engineer   58000        Pune   25  2900.0
9  110      Mehak         Accountant   36000   Jalandhar   30     0.0

In [77]:
df2["HRA"] = (df2["Salary"] * 0.1)
df2

,ID,Name,Post,Salary,City,Age,Bonus,DA,HRA
0,101,Harnoor,Developer,45000,Mohali,20,2250.0,2250.0,4500.0
1,102,Aditi,Data Analyst,38000,Chandigarh,22,0.0,1900.0,3800.0
2,103,Harsharan,Manager,65000,Ludhiana,28,3250.0,3250.0,6500.0
3,104,Ekam,Designer,42000,Amritsar,24,2100.0,2100.0,4200.0
4,105,Isha,Tester,35000,Patiala,23,0.0,1750.0,3500.0
5,106,Simran,Developer,52000,Delhi,26,2600.0,2600.0,5200.0
6,107,Karan,HR Executive,40000,Jaipur,27,0.0,2000.0,4000.0
7,108,Navya,Data Scientist,70000,Bangalore,29,3500.0,3500.0,7000.0
8,109,Arjun,Software Engineer,58000,Pune,25,2900.0,2900.0,5800.0
9,110,Mehak,Accountant,36000,Jalandhar,30,0.0,1800.0,3600.0

In [78]:
df2["DA"] = df2["Salary"] * 0.05
df2

,ID,Name,Post,Salary,City,Age,Bonus,DA,HRA
0,101,Harnoor,Developer,45000,Mohali,20,2250.0,2250.0,4500.0
1,102,Aditi,Data Analyst,38000,Chandigarh,22,0.0,1900.0,3800.0
2,103,Harsharan,Manager,65000,Ludhiana,28,3250.0,3250.0,6500.0
3,104,Ekam,Designer,42000,Amritsar,24,2100.0,2100.0,4200.0
4,105,Isha,Tester,35000,Patiala,23,0.0,1750.0,3500.0
5,106,Simran,Developer,52000,Delhi,26,2600.0,2600.0,5200.0
6,107,Karan,HR Executive,40000,Jaipur,27,0.0,2000.0,4000.0
7,108,Navya,Data Scientist,70000,Bangalore,29,3500.0,3500.0,7000.0
8,109,Arjun,Software Engineer,58000,Pune,25,2900.0,2900.0,5800.0
9,110,Mehak,Accountant,36000,Jalandhar,30,0.0,1800.0,3600.0

In [80]:
df2["Gross Salary"] = df2["Salary"] + df2["Bonus"] + df2["DA"] + df2["HRA"]
print(df2)

    ID       Name               Post  Salary        City  Age   Bonus      DA  \
0  101    Harnoor          Developer   45000      Mohali   20  2250.0  2250.0
1  102      Aditi       Data Analyst   38000  Chandigarh   22     0.0  1900.0
2  103  Harsharan            Manager   65000    Ludhiana   28  3250.0  3250.0
3  104       Ekam           Designer   42000    Amritsar   24  2100.0  2100.0
4  105       Isha             Tester   35000     Patiala   23     0.0  1750.0
5  106     Simran          Developer   52000       Delhi   26  2600.0  2600.0
6  107      Karan       HR Executive   40000      Jaipur   27     0.0  2000.0
7  108      Navya     Data Scientist   70000   Bangalore   29  3500.0  3500.0
8  109      Arjun  Software Engineer   58000        Pune   25  2900.0  2900.0
9  110      Mehak         Accountant   36000   Jalandhar   30     0.0  1800.0

      HRA  Gross Salary
0  4500.0       54000.0
1  3800.0       43700.0
2  6500.0       78000.0
3  4200.0       50400.0
4  3500.0       40250.0
5  5200.0       62400.0
6  4000.0       46000.0
7  7000.0       84000.0
8  5800.0       69600.0
9  3600.0       41400.0

In [81]:
df2

,ID,Name,Post,Salary,City,Age,Bonus,DA,HRA,Gross Salary
0,101,Harnoor,Developer,45000,Mohali,20,2250.0,2250.0,4500.0,54000.0
1,102,Aditi,Data Analyst,38000,Chandigarh,22,0.0,1900.0,3800.0,43700.0
2,103,Harsharan,Manager,65000,Ludhiana,28,3250.0,3250.0,6500.0,78000.0
3,104,Ekam,Designer,42000,Amritsar,24,2100.0,2100.0,4200.0,50400.0
4,105,Isha,Tester,35000,Patiala,23,0.0,1750.0,3500.0,40250.0
5,106,Simran,Developer,52000,Delhi,26,2600.0,2600.0,5200.0,62400.0
6,107,Karan,HR Executive,40000,Jaipur,27,0.0,2000.0,4000.0,46000.0
7,108,Navya,Data Scientist,70000,Bangalore,29,3500.0,3500.0,7000.0,84000.0
8,109,Arjun,Software Engineer,58000,Pune,25,2900.0,2900.0,5800.0,69600.0
9,110,Mehak,Accountant,36000,Jalandhar,30,0.0,1800.0,3600.0,41400.0

In [92]:
df2["net salary"] = df2["Gross Salary"] * 12

In [ ]:
# product id, name, price, qty, 
# 1. total price column also add, add column discount if total_price 5000 then 10 % otherwise 5 %
# 2. total 2000 free delivery
# 3. GST of 8 % on total_price

In [107]:
import pandas as pd
import numpy as np

data = {
    "product_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones",
             "Webcam", "Printer", "USB Cable", "Speaker", "Tablet"],
    "price": [55000, 800, 1500, 12000, 2500, 1800, 9000, 400, 3500, 25000],
    "qty": [2, 10, 5, 3, 8, 4, 2, 15, 6, 3]
}

df = pd.DataFrame(data)

df["Total_Price"] = df["price"] * df["qty"]

df["Discount"] = np.where(
    df["Total_Price"] > 5000,
    df["Total_Price"] * 0.10,
    df["Total_Price"] * 0.05
)

df["Free_Delivery"] = np.where(
    df["Total_Price"] > 2000,
    "Yes", "No"
)

df["GST"] = df["Total_Price"] * 0.08

df["Total_Bill"] = df["Total_Price"] - df["Discount"] + df["GST"]

print(df)

   product_id        name  price  qty  Total_Price  Discount Free_Delivery  \
0         101      Laptop  55000    2       110000   11000.0           Yes
1         102       Mouse    800   10         8000     800.0           Yes
2         103    Keyboard   1500    5         7500     750.0           Yes
3         104     Monitor  12000    3        36000    3600.0           Yes
4         105  Headphones   2500    8        20000    2000.0           Yes
5         106      Webcam   1800    4         7200     720.0           Yes
6         107     Printer   9000    2        18000    1800.0           Yes
7         108   USB Cable    400   15         6000     600.0           Yes
8         109     Speaker   3500    6        21000    2100.0           Yes
9         110      Tablet  25000    3        75000    7500.0           Yes

      GST  Total_Bill
0  8800.0    107800.0
1   640.0      7840.0
2   600.0      7350.0
3  2880.0     35280.0
4  1600.0     19600.0
5   576.0      7056.0
6  1440.0     17640.0
7   480.0      5880.0
8  1680.0     20580.0
9  6000.0     73500.0

In [1]:
# Test 1 

import numpy as np

sales = np.array([120, 150, 180, 90, 200, 250, 175, 300, 220, 160])

marks = np.array([
    [85, 78, 92],
    [67, 75, 80],
    [90, 88, 95],
    [55, 60, 65],
    [72, 85, 78]
])

prices = np.array([100, 250, 150, 500, 350, 120, 450, 200])

ages = np.array([22, 35, 28, 41, 19, 32, 25, 45, 30, 27])

In [4]:
print(sales.size)
print(sales.ndim)
print(sales.dtype)
print(sales.shape)

10
1
int64
(10,)

In [6]:
print(np.sum(sales))

1845

In [7]:
print(np.mean(sales))

184.5

In [10]:
print(np.max(sales))
print(np.min(sales))
print(np.argmax(sales))
print(np.argmin(sales))

300
90
7
3

In [14]:
print(sales[0])
print(sales[-1])
print(sales[4])
print(sales[2:7])

120
160
200
[180  90 200 250 175]

In [16]:
sales[::-1]

array([160, 220, 300, 175, 250, 200,  90, 180, 150, 120])

In [19]:
sales[sales > 200]

array([250, 300, 220])

In [21]:
ages[(ages >= 25) & (ages < 35)]

array([28, 32, 25, 30, 27])

In [28]:
marks = np.array([
    [85, 78, 92],
    [67, 75, 80],
    [90, 88, 95],
    [55, 60, 65],
    [72, 85, 78]
])

print(marks[0])
print(marks[1])

print(marks[:, 0])
print(marks[:, 1])

[85 78 92]
[67 75 80]
[85 67 90 55 72]
[78 75 88 60 85]

In [31]:
print(np.mean(marks[:, 0]))
print(np.mean(marks[:, 1]))
print(np.mean(marks[:, 2]))

73.8
77.2
82.0

In [33]:
new_price = np.array(prices  + prices * 0.1)
print(new_price)

[110. 275. 165. 550. 385. 132. 495. 220.]