In [ ]:
import numpy as np
import pandas as pd

emp = {
    "id" : [1, 2, 3, 4, 5],
    "name" : ["Harnoor", "Sahil", "Aditi", "Ram", "Shyam"],
    "age" : [12, 34, 56, 78, 22],
    "Dept" : ["CSE", "ECE", "CA", "BCA", "LAW"],
    "Salary" : [12000, 78000, 45000, 66000, 33000]
    }

df = pd.DataFrame(emp)

In [2]:
print(df)

   id     name  age Dept  Salary
0   1  Harnoor   12  CSE   12000
1   2    Sahil   34  ECE   78000
2   3    Aditi   56   CA   45000
3   4      Ram   78  BCA   66000
4   5    Shyam   22  LAW   33000

In [3]:
print(df.loc[0])

id              1
name      Harnoor
age            12
Dept          CSE
Salary      12000
Name: 0, dtype: object

In [4]:
print(df.loc[2, "Dept"])

CA

In [5]:
# get particular column
print(df.loc[:,"name"])

0    Harnoor
1      Sahil
2      Aditi
3        Ram
4      Shyam
Name: name, dtype: object

In [7]:
# get multiple columns

print(df.loc[:, ["name", "Salary"]])

      name  Salary
0  Harnoor   12000
1    Sahil   78000
2    Aditi   45000
3      Ram   66000
4    Shyam   33000

In [9]:
# get multiple rows

print(df.loc[[1, 2, 4]])

   id   name  age Dept  Salary
1   2  Sahil   34  ECE   78000
2   3  Aditi   56   CA   45000
4   5  Shyam   22  LAW   33000

In [14]:
df.loc[df["Salary"] > 30000]

   id   name  age Dept  Salary
1   2  Sahil   34  ECE   78000
2   3  Aditi   56   CA   45000
3   4    Ram   78  BCA   66000
4   5  Shyam   22  LAW   33000

In [15]:
df.loc[df["Dept"] == "CA"]

   id   name  age Dept  Salary
2   3  Aditi   56   CA   45000

In [16]:
data = {
    "product_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones",
             "Webcam", "Printer", "USB Cable", "Speaker", "Tablet"],
    "price": [55000, 800, 1500, 12000, 2500, 1800, 9000, 400, 3500, 25000],
    "qty": [2, 10, 5, 3, 8, 4, 2, 15, 6, 3]
}

df = pd.DataFrame(data)

In [17]:
print(df)

   product_id        name  price  qty
0         101      Laptop  55000    2
1         102       Mouse    800   10
2         103    Keyboard   1500    5
3         104     Monitor  12000    3
4         105  Headphones   2500    8
5         106      Webcam   1800    4
6         107     Printer   9000    2
7         108   USB Cable    400   15
8         109     Speaker   3500    6
9         110      Tablet  25000    3

In [18]:
# qty > 5
df.loc[df["qty"] > 5]

   product_id        name  price  qty
1         102       Mouse    800   10
4         105  Headphones   2500    8
7         108   USB Cable    400   15
8         109     Speaker   3500    6

In [19]:
# name = Tablet

df.loc[df["name"] == "Laptop"]

   product_id    name  price  qty
0         101  Laptop  55000    2

In [22]:
# 8th row
df.loc[8]

product_id        109
name          Speaker
price            3500
qty                 6
Name: 8, dtype: object

In [27]:
print(df.loc[:, ["price", "qty"]])

   price  qty
0  55000    2
1    800   10
2   1500    5
3  12000    3
4   2500    8
5   1800    4
6   9000    2
7    400   15
8   3500    6
9  25000    3

In [32]:
print(df.iloc[2, 3])

5

In [33]:
df2 = pd.DataFrame(emp)

In [35]:
df2["City"] = ["Goa", "Delhi", "Ambala", "Noida", "Amritsar"]

In [36]:
df2

   id     name  age Dept  Salary      City
0   1  Harnoor   12  CSE   12000       Goa
1   2    Sahil   34  ECE   78000     Delhi
2   3    Aditi   56   CA   45000    Ambala
3   4      Ram   78  BCA   66000     Noida
4   5    Shyam   22  LAW   33000  Amritsar

In [38]:
df2.iloc[[0, 1, 4]]

   id     name  age Dept  Salary      City
0   1  Harnoor   12  CSE   12000       Goa
1   2    Sahil   34  ECE   78000     Delhi
4   5    Shyam   22  LAW   33000  Amritsar

In [39]:
df2.iloc[0:3]

   id     name  age Dept  Salary    City
0   1  Harnoor   12  CSE   12000     Goa
1   2    Sahil   34  ECE   78000   Delhi
2   3    Aditi   56   CA   45000  Ambala

In [40]:
df2.iloc[-1]

id               5
name         Shyam
age             22
Dept           LAW
Salary       33000
City      Amritsar
Name: 4, dtype: object

In [41]:
# get first 3 rows and 2 columns

df2.iloc[0:3, 0:2]

   id     name
0   1  Harnoor
1   2    Sahil
2   3    Aditi

In [42]:
data = {
    "ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Rahul", "Priya", "Aman", "Neha", "Arjun",
        "Rahul", "Simran", "Vikas", None, "Priya"
    ],
    "Post": [
        "Manager", "Developer", "Accountant", "HR", "Designer",
        "Developer", "Manager", None, "Accountant", "Developer"
    ],
    "Salary": [
        60000, 50000, 45000, 40000, None,
        50000, 65000, 42000, 45000, 50000
    ],
    "City": [
        "Delhi", "Mumbai", "Chandigarh", "Ludhiana", "Amritsar",
        "Mumbai", None, "Delhi", "Chandigarh", "Mumbai"
    ],
    "Age": [
        35, 28, 32, 30, 27,
        None, 38, 29, 32, 28
    ]
} 
df=pd.DataFrame(data)
df

    ID    Name        Post   Salary        City   Age
0  101   Rahul     Manager  60000.0       Delhi  35.0
1  102   Priya   Developer  50000.0      Mumbai  28.0
2  103    Aman  Accountant  45000.0  Chandigarh  32.0
3  104    Neha          HR  40000.0    Ludhiana  30.0
4  105   Arjun    Designer      NaN    Amritsar  27.0
5  106   Rahul   Developer  50000.0      Mumbai   NaN
6  107  Simran     Manager  65000.0        None  38.0
7  108   Vikas        None  42000.0       Delhi  29.0
8  109    None  Accountant  45000.0  Chandigarh  32.0
9  110   Priya   Developer  50000.0      Mumbai  28.0

In [44]:
df.shape

(10, 6)

In [45]:
df.columns

Index(['ID', 'Name', 'Post', 'Salary', 'City', 'Age'], dtype='object')

In [ ]:
df.info()

# 9 indicates missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     int64
 1   Name    9 non-null      object
 2   Post    9 non-null      object
 3   Salary  9 non-null      float64
 4   City    9 non-null      object
 5   Age     9 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 612.0+ bytes

In [52]:
df.isnull()

      ID   Name   Post  Salary   City    Age
0  False  False  False   False  False  False
1  False  False  False   False  False  False
2  False  False  False   False  False  False
3  False  False  False   False  False  False
4  False  False  False    True  False  False
5  False  False  False   False  False   True
6  False  False  False   False   True  False
7  False  False   True   False  False  False
8  False   True  False   False  False  False
9  False  False  False   False  False  False

In [53]:
df.notnull()

     ID   Name   Post  Salary   City    Age
0  True   True   True    True   True   True
1  True   True   True    True   True   True
2  True   True   True    True   True   True
3  True   True   True    True   True   True
4  True   True   True   False   True   True
5  True   True   True    True   True  False
6  True   True   True    True  False   True
7  True   True  False    True   True   True
8  True  False   True    True   True   True
9  True   True   True    True   True   True

In [54]:
df.isnull().sum()

ID        0
Name      1
Post      1
Salary    1
City      1
Age       1
dtype: int64

In [55]:
df.count()

ID        10
Name       9
Post       9
Salary     9
City       9
Age        9
dtype: int64

In [62]:
df = df.fillna(0)

In [59]:
df.count()

ID        10
Name       9
Post       9
Salary     9
City       9
Age        9
dtype: int64

In [60]:
df

    ID    Name        Post   Salary        City   Age
0  101   Rahul     Manager  60000.0       Delhi  35.0
1  102   Priya   Developer  50000.0      Mumbai  28.0
2  103    Aman  Accountant  45000.0  Chandigarh  32.0
3  104    Neha          HR  40000.0    Ludhiana  30.0
4  105   Arjun    Designer      NaN    Amritsar  27.0
5  106   Rahul   Developer  50000.0      Mumbai   NaN
6  107  Simran     Manager  65000.0        None  38.0
7  108   Vikas        None  42000.0       Delhi  29.0
8  109    None  Accountant  45000.0  Chandigarh  32.0
9  110   Priya   Developer  50000.0      Mumbai  28.0

In [63]:
df.count()

ID        10
Name      10
Post      10
Salary    10
City      10
Age       10
dtype: int64

In [74]:
import pandas as pd
df3 = pd.read_excel("Employee.xlsx")

In [67]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [75]:
df3

    ID          Name                  Post  Salary       City  Age  Gender
0  101   Amit Sharma               Manager   65000      Delhi   35    Male
1  102    Neha Verma          HR Executive   42000     Mumbai   29  Female
2  103   Rahul Singh     Software Engineer   72000  Bengaluru   31    Male
3  104   Priya Gupta            Accountant   50000       Pune   28  Female
4  105   Karan Mehta       Sales Executive   39000     Jaipur   27    Male
5  106  Sneha Kapoor          Data Analyst   68000  Hyderabad   30  Female
6  107   Vikas Yadav           Team Leader   78000    Chennai   37    Male
7  108    Anjali Roy   Marketing Executive   47000    Kolkata   26  Female
8  109   Mohit Kumar  System Administrator   58000    Lucknow   33    Male
9  110  Pooja Mishra      Business Analyst   71000      Noida   32  Female

In [76]:
import pandas as pd
df3 = pd.read_excel("Employee.xlsx")

In [77]:
df3

    ID          Name                  Post  Salary       City  Age  Gender
0  101   Amit Sharma               Manager   65000      Delhi   35    Male
1  102    Neha Verma          HR Executive   42000     Mumbai   29  Female
2  103   Rahul Singh     Software Engineer   72000  Bengaluru   31    Male
3  104   Priya Gupta            Accountant   50000       Pune   28  Female
4  105   Karan Mehta       Sales Executive   39000     Jaipur   27    Male
5  106  Sneha Kapoor          Data Analyst   68000  Hyderabad   30  Female
6  107   Vikas Yadav           Team Leader   78000    Chennai   37    Male
7  108    Anjali Roy   Marketing Executive   47000    Kolkata   26  Female
8  109   Mohit Kumar  System Administrator   58000    Lucknow   33    Male
9  110  Pooja Mishra      Business Analyst   71000      Noida   32  Female