In [1]:
import pandas as pd

In [3]:
df3 = pd.read_excel("Employee.xlsx")
df3

    ID          Name                  Post  Salary       City  Age  Gender
0  101   Amit Sharma               Manager   65000      Delhi   35    Male
1  102    Neha Verma          HR Executive   42000     Mumbai   29  Female
2  103   Rahul Singh     Software Engineer   72000  Bengaluru   31    Male
3  104   Priya Gupta            Accountant   50000       Pune   28  Female
4  105   Karan Mehta       Sales Executive   39000     Jaipur   27    Male
5  106  Sneha Kapoor          Data Analyst   68000  Hyderabad   30  Female
6  107   Vikas Yadav           Team Leader   78000    Chennai   37    Male
7  108    Anjali Roy   Marketing Executive   47000    Kolkata   26  Female
8  109   Mohit Kumar  System Administrator   58000    Lucknow   33    Male
9  110  Pooja Mishra      Business Analyst   71000      Noida   32  Female

In [4]:
import os

print(os.getcwd())
print(os.path.abspath("Employee.xlsx"))

d:\LearningSkills\GenAI Training\Day 9
d:\LearningSkills\GenAI Training\Day 9\Employee.xlsx

In [5]:
import pandas as pd

df3 = pd.read_excel(os.path.abspath("Employee.xlsx"))
df3

    ID          Name                  Post  Salary       City  Age  Gender
0  101   Amit Sharma               Manager   65000      Delhi   35    Male
1  102    Neha Verma          HR Executive   42000     Mumbai   29  Female
2  103   Rahul Singh     Software Engineer   72000  Bengaluru   31    Male
3  104   Priya Gupta            Accountant   50000       Pune   28  Female
4  105   Karan Mehta       Sales Executive   39000     Jaipur   27    Male
5  106  Sneha Kapoor          Data Analyst   68000  Hyderabad   30  Female
6  107   Vikas Yadav           Team Leader   78000    Chennai   37    Male
7  108    Anjali Roy   Marketing Executive   47000    Kolkata   26  Female
8  109   Mohit Kumar  System Administrator   58000    Lucknow   33    Male
9  110  Pooja Mishra      Business Analyst   71000      Noida   32  Female

In [6]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Product Name": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer",
                     "USB Drive", "Router", "Webcam", "Headphones", "Speaker"],
    "Price": [55000, 500, 1200, 15000, 9000, 700, 2500, 1800, 2200, 3500],
    "Quantity": [10, 50, 30, 15, 8, 100, 20, 18, 25, 12],
    "Seller Name": ["Amit Traders", "Tech World", "Digital Hub", "Screen House",
                    "Print Solutions", "Storage Mart", "Net Zone", "Vision Tech",
                    "Audio Store", "Sound Hub"],
    "Mobile": [9876543210, 9876501234, 9811122233, 9898989898, 9123456780,
               9988776655, 9090909090, 9345678901, 9765432109, 9012345678],
    "City": ["Delhi", "Mumbai", "Pune", "Bengaluru", "Chennai",
             "Hyderabad", "Kolkata", "Jaipur", "Lucknow", "Ahmedabad"]
}

df = pd.DataFrame(data)

df

    ID Product Name  Price  Quantity      Seller Name      Mobile       City
0  101       Laptop  55000        10     Amit Traders  9876543210      Delhi
1  102        Mouse    500        50       Tech World  9876501234     Mumbai
2  103     Keyboard   1200        30      Digital Hub  9811122233       Pune
3  104      Monitor  15000        15     Screen House  9898989898  Bengaluru
4  105      Printer   9000         8  Print Solutions  9123456780    Chennai
5  106    USB Drive    700       100     Storage Mart  9988776655  Hyderabad
6  107       Router   2500        20         Net Zone  9090909090    Kolkata
7  108       Webcam   1800        18      Vision Tech  9345678901     Jaipur
8  109   Headphones   2200        25      Audio Store  9765432109    Lucknow
9  110      Speaker   3500        12        Sound Hub  9012345678  Ahmedabad

In [7]:
df.loc[1]

ID                     102
Product Name         Mouse
Price                  500
Quantity                50
Seller Name     Tech World
Mobile          9876501234
City                Mumbai
Name: 1, dtype: object

In [8]:
df.iloc[0:1]

    ID Product Name  Price  Quantity   Seller Name      Mobile   City
0  101       Laptop  55000        10  Amit Traders  9876543210  Delhi

In [9]:
import matplotlib.pyplot as plt

In [10]:
import seaborn as sns

In [11]:
import sklearn